# Generated by Django 5.2.6 on 2025-09-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='content',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='views_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
