# Generated by Django 5.2.6 on 2025-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_content_productmodel_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
