# Generated by Django 5.2.6 on 2025-09-04 11:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
