# Generated by Django 5.2.6 on 2025-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogmodel_content_blogmodel_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='views_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
