# Generated by Django 5.2.6 on 2025-09-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_content_blogmodel_content1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='content1',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image2',
        ),
    ]
