# Generated by Django 5.2.6 on 2025-09-07 07:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_content1_blogmodel_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image2',
            field=models.ImageField(default=1, upload_to='blog-post/'),
            preserve_default=False,
        ),
    ]
