# Generated by Django 5.2.6 on 2025-09-09 15:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_content_blogmodel_content1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='bio_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='bio_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='full_name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content1_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content1_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
