# Generated by Django 5.2.6 on 2025-09-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_authormodel_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_en',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_uz',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='bio_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='full_name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
