# Generated by Django 5.2.6 on 2025-09-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutmodel_content_en_aboutmodel_content_uz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='full_name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='authormodel',
            old_name='full_name_uz',
            new_name='title_uz',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='bio_uz',
        ),
    ]
