# Generated by Django 5.2.6 on 2025-09-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_full_name_en_authormodel_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='bio_uz',
            field=models.TextField(null=True),
        ),
    ]
